spring:
  application:
    name: llm_gateway

gateway:
  upstream:
    llamaurl: http://localhost:11434
    openaiurl: https://api.openai.com
    anthropicurl: https://api.anthropic.com
  ollama:
    models: llama3.1:8b,mistral
